-- NPCFlowFieldBridge.lua
-- Neutral shared backend for virtual flow field planner.

NPCFlowFieldBridge=NPCFlowFieldBridge or {}; NPCFlowFieldBridge.VERSION="2026-05-03-flow"; NPCFlowFieldBridge.Config=NPCFlowFieldBridge.Config or {enabled=true,stepRadiusBuckets=2,minScore=1.4,cacheSeconds=8}; NPCFlowFieldBridge.Cache=NPCFlowFieldBridge.Cache or {}
local function nset(k,d,mi,ma) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetNumber then return NPCLegacySettingsBridge.GetNumber(k,d,mi,ma) end return tonumber(d) or 0 end; local function bset(k,d) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetBool then return NPCLegacySettingsBridge.GetBool(k,d==true) end return d==true end
function NPCFlowFieldBridge.ApplySettings() local c=NPCFlowFieldBridge.Config; c.enabled=bset('Flow_Enabled',c.enabled~=false); c.stepRadiusBuckets=nset('Flow_StepRadiusBuckets',c.stepRadiusBuckets,1,8); c.minScore=nset('Flow_MinScore',c.minScore,-100,100); c.cacheSeconds=nset('Flow_CacheSeconds',c.cacheSeconds or 8,0,600) end
local function nowh() return getGameTime and (getGameTime():getWorldAgeHours() or 0) or 0 end
local function side(g) if NPCStrategicAIBridge and NPCStrategicAIBridge.GetGroupSide then local ok,s=pcall(function() return NPCStrategicAIBridge.GetGroupSide(g) end); if ok and s then return tostring(s) end end; return tostring(g and (g.patrolColor or g.faction or g.side or (g.hostile and 'red' or 'green')) or '') end
local function weights(g) local s=side(g); if s=='red' then return {green=2.2,black=1.9,blue=.15,red=-.55,baseNeed=.35,noise=.25,threat=.2,zombie=-.4} elseif s=='green' then return {red=2.2,black=1.9,blue=.15,green=-.55,baseNeed=.35,noise=.25,threat=.2,zombie=-.4} elseif s=='blue' then return {baseNeed=1.3,loot=.8,threat=-.7,zombie=-.5,black=-.9,noise=-.15} elseif s=='black' then return {red=1.4,green=1.4,blue=1.1,noise=.75,threat=.65,zombie=-.25} end; return {baseNeed=.7,noise=.3,threat=.2,zombie=-.25} end
function NPCFlowFieldBridge.SuggestVirtualStep(g) if not NPCFlowFieldBridge.Config.enabled or not g or not g.x or g.activated or g.inBattle or not(NPCInfluenceFieldBridge and NPCInfluenceFieldBridge.FindBestNeighbor) then return nil end; local k=tostring(g.id or 'g')..':'..tostring(math.floor(g.x))..':'..tostring(math.floor(g.y)); local c=NPCFlowFieldBridge.Cache[k]; local n=nowh(); if c and n-(c.t or 0)<(NPCFlowFieldBridge.Config.cacheSeconds or 8)/3600 then return c.step end; local st=NPCInfluenceFieldBridge.FindBestNeighbor(g.x,g.y,weights(g),NPCFlowFieldBridge.Config.stepRadiusBuckets or 2); if st and (tonumber(st.score) or 0)>=(NPCFlowFieldBridge.Config.minScore or 1.4) then st.spawnClass='flow'; st.flowScore=st.score; NPCFlowFieldBridge.Cache[k]={t=n,step=st}; return st end; NPCFlowFieldBridge.Cache[k]={t=n}; return nil end
NPCFlowFieldBridge.ApplySettings()
