-- NPCFormationSlotsBridge.lua
-- Neutral shared backend for formation slot planner.

NPCFormationSlotsBridge=NPCFormationSlotsBridge or {}; NPCFormationSlotsBridge.VERSION="2026-05-03-slots"; NPCFormationSlotsBridge.Config=NPCFormationSlotsBridge.Config or {enabled=true,slotSpacing=1.55,personalSpace=1.05,maxSlots=18}
local function nset(k,d,mi,ma) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetNumber then return NPCLegacySettingsBridge.GetNumber(k,d,mi,ma) end return tonumber(d) or 0 end; local function bset(k,d) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetBool then return NPCLegacySettingsBridge.GetBool(k,d==true) end return d==true end
function NPCFormationSlotsBridge.ApplySettings() local c=NPCFormationSlotsBridge.Config; c.enabled=bset('FormationSlots_Enabled',c.enabled~=false); c.slotSpacing=nset('FormationSlots_SlotSpacing',c.slotSpacing,.5,5); c.personalSpace=nset('FormationSlots_PersonalSpace',c.personalSpace,.2,5); c.maxSlots=nset('FormationSlots_MaxSlots',c.maxSlots,2,64) end
local function id(b,br) if br and (br.memberIndex or br.id or br.uid) then return tonumber(br.memberIndex or br.id or 1) or 1 end; if NPCUtils and NPCUtils.GetCharacterID then local ok,v=pcall(function() return NPCUtils.GetCharacterID(b) end); if ok and v then return tonumber(v) or 1 end end; return 1 end
function NPCFormationSlotsBridge.GetSlotPoint(player,br,b,formation,distance) if not NPCFormationSlotsBridge.Config.enabled or not player then return nil end; local idx=((math.max(1,id(b,br))-1)%(NPCFormationSlotsBridge.Config.maxSlots or 18))+1; local row=math.floor((idx-1)/2)+1; local side=(idx%2==0) and 1 or -1; local a=0; if player.getDirectionAngle then local ok,v=pcall(function() return player:getDirectionAngle() end); if ok and v then a=math.rad(tonumber(v) or 0) end end; local backX,backY=-math.cos(a),-math.sin(a); local rightX,rightY=-math.sin(a),math.cos(a); local spacing=NPCFormationSlotsBridge.Config.slotSpacing or 1.55; local back=(tonumber(distance) or 3)+row*.85; local lat=side*spacing*row; formation=tostring(formation or 'close'); if formation=='ring' or formation=='bodyguard' then local ring=math.floor((idx-1)/8); local pos=(idx-1)%8; local radius=(tonumber(distance) or 3)+ring*spacing*1.2; local aa=a+(pos*(math.pi*2/8)); return player:getX()+math.cos(aa)*radius, player:getY()+math.sin(aa)*radius, player:getZ() end; if formation=='line' then back=tonumber(distance) or 3; lat=(idx-9)*spacing elseif formation=='wedge' then back=(tonumber(distance) or 3)+row*1.2; lat=side*row*spacing*1.15 elseif formation=='wide' then lat=side*row*spacing*1.65; back=back+row*.4 end; return player:getX()+backX*back+rightX*lat, player:getY()+backY*back+rightY*lat, player:getZ() end
function NPCFormationSlotsBridge.GetAnchorSlotPoint(anchor,br,b,formation,distance) if not NPCFormationSlotsBridge.Config.enabled or type(anchor)~='table' or not (anchor.x and anchor.y) then return nil end; local idx=((math.max(1,id(b,br))-1)%(NPCFormationSlotsBridge.Config.maxSlots or 18))+1; local row=math.floor((idx-1)/2)+1; local side=(idx%2==0) and 1 or -1; local a=math.rad(tonumber(anchor.facingAngle) or 0); local backX,backY=-math.cos(a),-math.sin(a); local rightX,rightY=-math.sin(a),math.cos(a); local spacing=NPCFormationSlotsBridge.Config.slotSpacing or 1.55; local base=tonumber(distance) or 2.0; local back=row*.65; local lat=side*spacing*row; formation=tostring(formation or 'close'); if formation=='ring' or formation=='bodyguard' then local ring=math.floor((idx-1)/8); local pos=(idx-1)%8; local radius=math.max(1.4,base)+ring*spacing*1.1; local aa=a+(pos*(math.pi*2/8)); return tonumber(anchor.x)+math.cos(aa)*radius, tonumber(anchor.y)+math.sin(aa)*radius, tonumber(anchor.z) or 0 end; if formation=='line' then back=0; lat=side*spacing*row elseif formation=='wedge' then back=row*1.1; lat=side*row*spacing*1.15 elseif formation=='wide' then lat=side*row*spacing*1.85; back=row*.9 else back=row*.55; lat=side*spacing*math.max(1,row*.7) end; return tonumber(anchor.x)+backX*back+rightX*lat, tonumber(anchor.y)+backY*back+rightY*lat, tonumber(anchor.z) or 0 end
NPCFormationSlotsBridge.ApplySettings()
