-- NPCGOAPLiteBridge.lua
-- Neutral shared backend for GOAP-lite planner.

require "NPCCore/NPCWorkSchedulerBridge"

NPCGOAPLiteBridge=NPCGOAPLiteBridge or {}; NPCGOAPLiteBridge.VERSION="2026-05-24-goap-lite-governed"; NPCGOAPLiteBridge.Config=NPCGOAPLiteBridge.Config or {enabled=true,cooldownSeconds=5,maxPlansPerTick=6}; NPCGOAPLiteBridge.LastPlan=NPCGOAPLiteBridge.LastPlan or {}; NPCGOAPLiteBridge.TickPlans=0
local function nset(k,d,mi,ma) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetNumber then return NPCLegacySettingsBridge.GetNumber(k,d,mi,ma) end return tonumber(d) or 0 end; local function bset(k,d) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetBool then return NPCLegacySettingsBridge.GetBool(k,d==true) end return d==true end; local function now() return getTimestampMs and getTimestampMs() or (getGameTime and math.floor((getGameTime():getWorldAgeHours() or 0)*3600000) or 0) end
function NPCGOAPLiteBridge.ApplySettings() local c=NPCGOAPLiteBridge.Config; c.enabled=bset('GOAPLite_Enabled',c.enabled~=false); c.cooldownSeconds=nset('GOAPLite_CooldownSeconds',c.cooldownSeconds,0,300); c.maxPlansPerTick=nset('GOAPLite_MaxPlansPerTick',c.maxPlansPerTick,1,100) end
local function key(b,br) if br and (br.id or br.uid) then return tostring(br.id or br.uid) end; if NPCUtils and NPCUtils.GetCharacterID then local ok,id=pcall(function() return NPCUtils.GetCharacterID(b) end); if ok and id then return tostring(id) end end; return tostring(b) end
function NPCGOAPLiteBridge.SuggestState(b,br,states) if not NPCGOAPLiteBridge.Config.enabled or not br or not states or NPCGOAPLiteBridge.TickPlans>=(NPCGOAPLiteBridge.Config.maxPlansPerTick or 6) then return nil end; local k=key(b,br); local ms=now(); if ms-(tonumber(NPCGOAPLiteBridge.LastPlan[k]) or 0)<(NPCGOAPLiteBridge.Config.cooldownSeconds or 5)*1000 then return nil end; NPCGOAPLiteBridge.LastPlan[k]=ms; NPCGOAPLiteBridge.TickPlans=NPCGOAPLiteBridge.TickPlans+1; if br.weapons then for _,slot in pairs(br.weapons) do if type(slot)=='table' and slot.name and (tonumber(slot.bulletsLeft) or 0)<=0 and ((tonumber(slot.magCount) or 0)>0 or (tonumber(slot.ammoCount) or 0)>0) then return states.ReloadWeapon,'goap-lite reload' end end end; local nd=br.needs or {}; if (tonumber(nd.rest) or 0)>.82 then return states.SleepRest,'goap-lite rest' end; if (tonumber(nd.food) or 0)>.74 or (tonumber(nd.water) or 0)>.78 then return states.EatDrink,'goap-lite food/water' end; if br.homeBaseId and br.baseDuty=='storage' then return states.LootArea,'goap-lite logistics' end; if br.homeBaseId and (br.baseDuty=='guard' or br.baseDuty=='patrol') then return states.DefendBase,'goap-lite base duty' end; return nil end
local function tick() NPCGOAPLiteBridge.TickPlans=0; if ZombRand and ZombRand(300)==0 then NPCGOAPLiteBridge.ApplySettings() end end; NPCGOAPLiteBridge.ApplySettings(); if NPCWorkSchedulerBridge and NPCWorkSchedulerBridge.RegisterTickJob and not NPCGOAPLiteBridge._registered then NPCGOAPLiteBridge._registered=true; NPCWorkSchedulerBridge.RegisterTickJob("NPCGOAPLiteBridge", tick, "system", 1) elseif Events and Events.OnTick and not NPCGOAPLiteBridge._registered then NPCGOAPLiteBridge._registered=true; Events.OnTick.Add(tick) end
