-- NPCProxySimulationBridge.lua
-- Neutral shared backend for virtual proxy battle simulation.

NPCProxySimulationBridge=NPCProxySimulationBridge or {}; NPCProxySimulationBridge.VERSION="2026-05-03-proxy"; NPCProxySimulationBridge.Config=NPCProxySimulationBridge.Config or {enabled=true,battleMultiplier=1,maxLossPerTick=2,moraleInfluence=true}
local function nset(k,d,mi,ma) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetNumber then return NPCLegacySettingsBridge.GetNumber(k,d,mi,ma) end return tonumber(d) or 0 end; local function bset(k,d) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetBool then return NPCLegacySettingsBridge.GetBool(k,d==true) end return d==true end
function NPCProxySimulationBridge.ApplySettings() local c=NPCProxySimulationBridge.Config; c.enabled=bset('ProxyLOD_Enabled',c.enabled~=false); c.battleMultiplier=nset('ProxyLOD_BattleMultiplier',c.battleMultiplier,0,10); c.maxLossPerTick=nset('ProxyLOD_MaxLossPerTick',c.maxLossPerTick,0,20); c.moraleInfluence=bset('ProxyLOD_MoraleInfluence',c.moraleInfluence~=false) end
local function power(g) if not g then return 0 end; local count=tonumber(g.count) or #(g.members or {}) or 0; local p=count*18+(tonumber(g.combatPower) or 0)*.35; if g.mercenaryElite or g.elite then p=p+count*10 end; if g.hostile then p=p+4 end; if NPCProxySimulationBridge.Config.moraleInfluence then p=p+((tonumber(g.morale) or .5)-.5)*count*8-((tonumber(g.fear) or 0)*count*5) end; return p end
function NPCProxySimulationBridge.RollVirtualBattleLoss(g,att) if not NPCProxySimulationBridge.Config.enabled then return nil end; local count=tonumber(g and g.count) or #(g and g.members or {}) or 0; if count<=0 then return 0 end; local pressure=(power(att)/math.max(1,power(g)))*50*(NPCProxySimulationBridge.Config.battleMultiplier or 1); local roll=ZombRand and ZombRand(100) or math.random(0,99); local loss=0; if roll<pressure then loss=1 end; if count>3 and roll+35<pressure then loss=loss+1 end; if count>7 and roll+70<pressure then loss=loss+1 end; local maxLoss=NPCProxySimulationBridge.Config.maxLossPerTick or 2; if loss>maxLoss then loss=maxLoss end; if loss>count then loss=count end; return loss end
NPCProxySimulationBridge.ApplySettings()
