-- NPCTacticalCostFieldBridge.lua
-- Neutral shared backend for tactical cost-field planner.

require "NPCCore/NPCLegacySettingsBridge"
require "NPCCore/NPCInfluenceFieldBridge"

NPCTacticalCostFieldBridge=NPCTacticalCostFieldBridge or {}; NPCTacticalCostFieldBridge.VERSION="2026-05-03-tactical-cost"; NPCTacticalCostFieldBridge.Config=NPCTacticalCostFieldBridge.Config or {enabled=true,sampleRadius=7,samples=12,threatWeight=1.4,zombieWeight=.7,noiseWeight=.25}
local function nset(k,d,mi,ma) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetNumber then return NPCLegacySettingsBridge.GetNumber(k,d,mi,ma) end return tonumber(d) or 0 end; local function bset(k,d) if NPCLegacySettingsBridge and NPCLegacySettingsBridge.GetBool then return NPCLegacySettingsBridge.GetBool(k,d==true) end return d==true end
function NPCTacticalCostFieldBridge.ApplySettings() local c=NPCTacticalCostFieldBridge.Config; c.enabled=bset('TacticalCost_Enabled',c.enabled~=false); c.sampleRadius=nset('TacticalCost_SampleRadius',c.sampleRadius,2,40); c.samples=nset('TacticalCost_Samples',c.samples,4,64); c.threatWeight=nset('TacticalCost_ThreatWeight',c.threatWeight,0,10); c.zombieWeight=nset('TacticalCost_ZombieWeight',c.zombieWeight,0,10); c.noiseWeight=nset('TacticalCost_NoiseWeight',c.noiseWeight,0,10) end
local function d2(x1,y1,x2,y2) local dx=(x1 or 0)-(x2 or 0); local dy=(y1 or 0)-(y2 or 0); return dx*dx+dy*dy end
function NPCTacticalCostFieldBridge.GetCost(x,y,threat) local c=0; if NPCInfluenceFieldBridge and NPCInfluenceFieldBridge.GetField then c=c+(NPCInfluenceFieldBridge.GetField(x,y,'threat') or 0)*(NPCTacticalCostFieldBridge.Config.threatWeight or 1.4)+(NPCInfluenceFieldBridge.GetField(x,y,'zombie') or 0)*(NPCTacticalCostFieldBridge.Config.zombieWeight or .7)+(NPCInfluenceFieldBridge.GetField(x,y,'noise') or 0)*(NPCTacticalCostFieldBridge.Config.noiseWeight or .25) end; if threat and threat.x then local dd=d2(x,y,threat.x,threat.y); if dd<100 then c=c+(100-dd)*.18 end end; return c end
function NPCTacticalCostFieldBridge.FindSaferPoint(b,br,threat,mode) if not NPCTacticalCostFieldBridge.Config.enabled or not b or not b.getX then return nil end; local bx,by,bz=b:getX(),b:getY(),b:getZ(); local r=NPCTacticalCostFieldBridge.Config.sampleRadius; local samples=NPCTacticalCostFieldBridge.Config.samples; local ax,ay=0,0; if threat and threat.x then ax=bx-threat.x; ay=by-threat.y; local l=math.sqrt(ax*ax+ay*ay); if l>.01 then ax=ax/l; ay=ay/l end end; local best,score=nil,1000000; for i=1,samples do local a=(i/samples)*6.28318; local tx=bx+math.cos(a)*r; local ty=by+math.sin(a)*r; local sc=NPCTacticalCostFieldBridge.GetCost(tx,ty,threat); if mode=='flee' then sc=sc-(((tx-bx)*ax+(ty-by)*ay)*2) end; if sc<score then score=sc; best={x=math.floor(tx),y=math.floor(ty),z=bz,cost=sc} end end; return best end
NPCTacticalCostFieldBridge.ApplySettings()
